// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clicks.sql

package sqlitegen

import (
	"context"
)

const clicksByDay = `-- name: ClicksByDay :many
SELECT (ts / 86400) * 86400 AS day_start,
       COUNT(*)              AS hits
FROM   clicks
WHERE  slug = ?
  AND  ts >= ?
GROUP  BY day_start
ORDER  BY day_start ASC
`

type ClicksByDayParams struct {
	Slug string
	Ts   int64
}

type ClicksByDayRow struct {
	DayStart int64
	Hits     int64
}

// Aggregated daily counts for the dashboard's per-link sparkline.
func (q *Queries) ClicksByDay(ctx context.Context, arg ClicksByDayParams) ([]ClicksByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, clicksByDay, arg.Slug, arg.Ts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClicksByDayRow{}
	for rows.Next() {
		var i ClicksByDayRow
		if err := rows.Scan(&i.DayStart, &i.Hits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countClicksForSlug = `-- name: CountClicksForSlug :one
SELECT COUNT(*) FROM clicks WHERE slug = ?
`

func (q *Queries) CountClicksForSlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClicksForSlug, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertClick = `-- name: InsertClick :exec

INSERT INTO clicks (slug, ts, country, user_agent, referrer, ip_hash, fly_region)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertClickParams struct {
	Slug      string
	Ts        int64
	Country   string
	UserAgent string
	Referrer  string
	IpHash    string
	FlyRegion string
}

// queries for the analytics bounded context.
func (q *Queries) InsertClick(ctx context.Context, arg InsertClickParams) error {
	_, err := q.db.ExecContext(ctx, insertClick,
		arg.Slug,
		arg.Ts,
		arg.Country,
		arg.UserAgent,
		arg.Referrer,
		arg.IpHash,
		arg.FlyRegion,
	)
	return err
}

const listClicksForSlug = `-- name: ListClicksForSlug :many
SELECT id, slug, ts, country, user_agent, referrer, ip_hash, fly_region
FROM   clicks
WHERE  slug = ?
  AND  ts < ?
ORDER  BY ts DESC
LIMIT  ?
`

type ListClicksForSlugParams struct {
	Slug  string
	Ts    int64
	Limit int64
}

func (q *Queries) ListClicksForSlug(ctx context.Context, arg ListClicksForSlugParams) ([]Click, error) {
	rows, err := q.db.QueryContext(ctx, listClicksForSlug, arg.Slug, arg.Ts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Click{}
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Ts,
			&i.Country,
			&i.UserAgent,
			&i.Referrer,
			&i.IpHash,
			&i.FlyRegion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
