// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package sqlitegen

import (
	"context"
)

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links WHERE slug = ?
`

func (q *Queries) DeleteLink(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, deleteLink, slug)
	return err
}

const getActiveLink = `-- name: GetActiveLink :one
SELECT slug, target_url, created_at, expires_at, password_hash,
       max_clicks, click_count, note, created_by
FROM   links
WHERE  slug = ?
  AND  (expires_at IS NULL OR expires_at > ?)
  AND  (max_clicks IS NULL OR click_count < max_clicks)
LIMIT  1
`

type GetActiveLinkParams struct {
	Slug      string
	ExpiresAt *int64
}

// Hot path: the only query that runs on the redirect critical path.
// Returns the link only if it isn't expired and hasn't exhausted max_clicks.
func (q *Queries) GetActiveLink(ctx context.Context, arg GetActiveLinkParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, getActiveLink, arg.Slug, arg.ExpiresAt)
	var i Link
	err := row.Scan(
		&i.Slug,
		&i.TargetUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.ClickCount,
		&i.Note,
		&i.CreatedBy,
	)
	return i, err
}

const getLink = `-- name: GetLink :one
SELECT slug, target_url, created_at, expires_at, password_hash,
       max_clicks, click_count, note, created_by
FROM   links
WHERE  slug = ?
LIMIT  1
`

func (q *Queries) GetLink(ctx context.Context, slug string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLink, slug)
	var i Link
	err := row.Scan(
		&i.Slug,
		&i.TargetUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxClicks,
		&i.ClickCount,
		&i.Note,
		&i.CreatedBy,
	)
	return i, err
}

const incrementClickCount = `-- name: IncrementClickCount :exec
UPDATE links SET click_count = click_count + 1 WHERE slug = ?
`

func (q *Queries) IncrementClickCount(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, incrementClickCount, slug)
	return err
}

const insertLink = `-- name: InsertLink :exec

INSERT INTO links (
    slug, target_url, created_at, expires_at, password_hash,
    max_clicks, note, created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertLinkParams struct {
	Slug         string
	TargetUrl    string
	CreatedAt    int64
	ExpiresAt    *int64
	PasswordHash *string
	MaxClicks    *int64
	Note         string
	CreatedBy    string
}

// queries for the shortener bounded context.
func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertLink,
		arg.Slug,
		arg.TargetUrl,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.PasswordHash,
		arg.MaxClicks,
		arg.Note,
		arg.CreatedBy,
	)
	return err
}

const listLinks = `-- name: ListLinks :many
SELECT slug, target_url, created_at, expires_at, password_hash,
       max_clicks, click_count, note, created_by
FROM   links
WHERE  created_at < ?
ORDER  BY created_at DESC
LIMIT  ?
`

type ListLinksParams struct {
	CreatedAt int64
	Limit     int64
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinks, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.Slug,
			&i.TargetUrl,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.PasswordHash,
			&i.MaxClicks,
			&i.ClickCount,
			&i.Note,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :exec
UPDATE links
SET    target_url    = ?,
       expires_at    = ?,
       password_hash = ?,
       max_clicks    = ?,
       note          = ?
WHERE  slug = ?
`

type UpdateLinkParams struct {
	TargetUrl    string
	ExpiresAt    *int64
	PasswordHash *string
	MaxClicks    *int64
	Note         string
	Slug         string
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) error {
	_, err := q.db.ExecContext(ctx, updateLink,
		arg.TargetUrl,
		arg.ExpiresAt,
		arg.PasswordHash,
		arg.MaxClicks,
		arg.Note,
		arg.Slug,
	)
	return err
}
