// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

type Click struct {
	ID        int64
	Slug      string
	Ts        int64
	Country   string
	UserAgent string
	Referrer  string
	IpHash    string
	FlyRegion string
}

type Link struct {
	Slug         string
	TargetUrl    string
	CreatedAt    int64
	ExpiresAt    *int64
	PasswordHash *string
	MaxClicks    *int64
	ClickCount   int64
	Note         string
	CreatedBy    string
}
