// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

import (
	"context"
)

type Querier interface {
	// Aggregated daily counts for the dashboard's per-link sparkline.
	ClicksByDay(ctx context.Context, arg ClicksByDayParams) ([]ClicksByDayRow, error)
	CountClicksForSlug(ctx context.Context, slug string) (int64, error)
	DeleteLink(ctx context.Context, slug string) error
	// Hot path: the only query that runs on the redirect critical path.
	// Returns the link only if it isn't expired and hasn't exhausted max_clicks.
	GetActiveLink(ctx context.Context, arg GetActiveLinkParams) (Link, error)
	GetLink(ctx context.Context, slug string) (Link, error)
	IncrementClickCount(ctx context.Context, slug string) error
	// queries for the analytics bounded context.
	InsertClick(ctx context.Context, arg InsertClickParams) error
	// queries for the shortener bounded context.
	InsertLink(ctx context.Context, arg InsertLinkParams) error
	ListClicksForSlug(ctx context.Context, arg ListClicksForSlugParams) ([]Click, error)
	ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) error
}

var _ Querier = (*Queries)(nil)
